-- Copyright (C) 2026 DPG Supply
--
-- This program is free software: you can redistribute it and/or modify
-- it under the terms of the GNU General Public License as published by
-- the Free Software Foundation, either version 3 of the License, or
-- (at your option) any later version.

CREATE TABLE llx_svc_request(
	rowid                  INTEGER AUTO_INCREMENT PRIMARY KEY,
	ref                    VARCHAR(30)   NOT NULL,
	entity                 INTEGER       NOT NULL DEFAULT 1,
	fk_soc                 INTEGER       NOT NULL,
	fk_product             INTEGER       NOT NULL,
	serial_number          VARCHAR(128),
	fk_contact             INTEGER,
	customer_site          VARCHAR(255),
	fk_project             INTEGER,
	fk_commande            INTEGER,
	fk_expedition_origin   INTEGER,
	fk_lot                 INTEGER,
	issue_description      TEXT,
	issue_date             DATETIME,
	reported_via           VARCHAR(50),
	fk_pbxcall             INTEGER,
	resolution_type        VARCHAR(50),
	resolution_notes       TEXT,
	fk_warranty            INTEGER,
	warranty_status        VARCHAR(20)   DEFAULT 'none',
	billable               TINYINT       DEFAULT 0,
	fk_facture             INTEGER,
	serial_in              VARCHAR(128),
	serial_out             VARCHAR(128),
	fk_warehouse_source    INTEGER,
	fk_warehouse_return    INTEGER,
	outbound_carrier       VARCHAR(100),
	outbound_tracking      VARCHAR(100),
	date_shipped           DATETIME,
	fk_shipment            INTEGER,
	return_carrier         VARCHAR(100),
	return_tracking        VARCHAR(100),
	date_return_expected   DATE,
	date_return_received   DATETIME,
	return_reminder_count  INTEGER       DEFAULT 0,
	fk_reception           INTEGER,
	fk_intervention        INTEGER,
	fk_user_assigned       INTEGER,
	status                 INTEGER       NOT NULL DEFAULT 0,
	date_creation          DATETIME      NOT NULL,
	date_validation        DATETIME,
	date_closed            DATETIME,
	tms                    TIMESTAMP,
	fk_user_creat          INTEGER,
	fk_user_valid          INTEGER,
	fk_user_close          INTEGER,
	import_key             VARCHAR(14),
	model_pdf              VARCHAR(255),
	last_main_doc          VARCHAR(255),
	note_private           TEXT,
	note_public            TEXT
) ENGINE=innodb;
